### ISSUE TITLE
Is there a manual?

### ISSUE THREAD

**Issue by twixwix** [patriceckhart/TYPO3GoogleReviews#1]
How can I add my API keys? Only add content element or do I need more?

**Comment by patriceckhart** [comment]
Yes, you can set your Place ID and API Key directly in the CE. 

Please note: Google wants money for API calls since July 2018. But there is a free quota. You need to enable the Google Place API in your Google Account with which you generated your API Key.

To avoid costs, you can fork my extension and call an XML/JSON file (placed in fileadmin) instead of the direct call.
